import About from "./About";
import CardById from "./Catalog/CardById";
import Catalog from "./Catalog/index";
import Contacts from "./Contacts";
import Delivery from "./Delivery";
import Exchange from "./Exchange";
import Home from "./Home";
import Order from "./Order";
import SecondPage from "./SecondPage";
import Error from "./error";
export { About, CardById, Catalog, Contacts, Delivery, Error, Exchange, Home, Order, SecondPage };
